version: "3.9"
services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  api:
    build:
      dockerfile: Dockerfile
      context: packages/backend/src/Bsc.Function
    ports:
      - "7071:7071"
    env_file:
        .env.local
    depends_on:
      - storage
  site:
    build:
      dockerfile: Dockerfile
      context: packages/site
    ports:
      - "3000:3000"
    depends_on:
      - api
      - storage
