name: Main
on: [push]
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TERRAFORM_VERSION: 1.0.1
jobs:
  test:
    name: Build And Deploy
    runs-on: ubuntu-20.04
    environment: prod
    env:
      TARGET_ENV: prod
      PLAN_PATH: ${{ github.workspace }}/infra/prod/prod.tfplan
      ASSETS_PATH: ${{ github.workspace}}/src/assets
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - run: yarn install
        name: Install Dependencies

      - run: yarn test
        name: Run Unit Tests

      - run: yarn e2e
        name: Run UI Tests

      - run: ${{ github.workspace }}/scripts/optimize-images.sh
        name: Optimize Images

      - run: yarn build
        name: Build Site

      - run: ${{ github.workspace }}/scripts/install-terraform.sh
        name: Install Terraform

      - run: ${{ github.workspace }}/scripts/init-terraform.sh
        name: Initialize Terraform

      - run: ${{ github.workspace }}/scripts/plan-terraform.sh
        name: Create Terraform Plan

      - run: ${{ github.workspace }}/scripts/apply-terraform.sh
        name: Apply Terraform Plan

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
